# Generated by Django 2.2.4 on 2019-08-26 12:00

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('phone1', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
                ('phone2', models.CharField(max_length=200)),
                ('name3', models.CharField(max_length=200)),
                ('phone3', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('were_threats_made', models.BooleanField()),
                ('police_contacted', models.BooleanField()),
                ('in_rave', models.BooleanField()),
                ('in_police_backend', models.BooleanField()),
                ('has_been_swatted', models.BooleanField()),
                ('address', models.CharField(max_length=200)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('streaming_url', models.CharField(max_length=200)),
                ('concerns', models.TextField()),
                ('place_details', models.TextField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
